using wServer.logic.behaviors;
using wServer.logic.loot;
using wServer.logic.transitions;
using common.resources;
//by GhostMaree
namespace wServer.logic
{
    partial class BehaviorDb
    {
        private _ QuestChests = () => Behav()
            .Init("Quest Chest",
                new State(
                    new ScaleHP2(100, 1, 15),
                    new State("Idle",
                        new Flash(0xFFFFFF, 0.5, 1),
                        new TimedTransition(5, "UnsetEffect")
                    ),
                    new State("UnsetEffect")
                ),
                new Threshold(0.01,
                    new ItemLoot(item: "Holy Water", probability: 0.4),
                    new ItemLoot(item: "Snake Skin Armor", probability: 0.05),
                    new ItemLoot(item: "Snake Skin Shield", probability: 0.05),
                    new ItemLoot(item: "Snake Eye Ring", probability: 0.05),
                    new ItemLoot(item: "Experimental Ring", probability: 0.005),
                    new ItemLoot(item: "St. Abraham's Wand", probability: 0.004),
                    new ItemLoot(item: "Chasuble of Holy Light", probability: 0.08),
                    new ItemLoot(item: "Ring of Divine Faith", probability: 0.05),
                    new ItemLoot(item: "Sprite Wand", probability: 0.008),
                     new ItemLoot(item: "Potion of Luck", probability: 0.3),
                    new ItemLoot(item: "Potion of Defense", probability: 0.3),
                    new ItemLoot(item: "Potion of Attack", probability: 0.3),
                    new ItemLoot(item: "Potion of Vitality", probability: 0.3),
                    new ItemLoot(item: "Potion of Wisdom", probability: 0.3),
                    new ItemLoot(item: "Potion of Speed", probability: 0.3),
                    new ItemLoot(item: "Potion of Dexterity", probability: 0.3),
                    new ItemLoot(item: "Wine Cellar Incantation", probability: 0.05),
                    new ItemLoot(item: "Etherite Dagger", probability: 0.01),
                    new ItemLoot(item: "Ghastly Drape", probability: 0.01),
                    new ItemLoot(item: "Mantle of Skuld", probability: 0.01),
                    new ItemLoot(item: "Spectral Ring of Horrors", probability: 0.01),
                    new ItemLoot(item: "Wand of the Bulwark", probability: 0.001),
                    new ItemLoot(item: "Staff of Extreme Prejudice", probability: 0.001),
                    new ItemLoot(item: "Cloak of the Planewalker", probability: 0.001),
                    new ItemLoot(item: "Demon Blade", probability: 0.001),
                    new ItemLoot(item: "Doom Bow", probability: 0.001),
                    new ItemLoot(item: "Murky Toxin", probability: 0.001),
                    new ItemLoot(item: "Conducting Wand", probability: 0.001),
                    new ItemLoot(item: "Robe of the Mad Scientist", probability: 0.001),
                    new ItemLoot(item: "Scepter of Fulmination", probability: 0.001),
                    new ItemLoot(item: "Harlequin Armor", probability: 0.001),
                    new ItemLoot(item: "Prism of Dancing Swords", probability: 0.001),
                    new ItemLoot(item: "Plague Poison", probability: 0.001),
                    new ItemLoot(item: "Resurrected Warrior's Armor", probability: 0.001),
                    new ItemLoot(item: "Tome of Purification", probability: 0.001),
                    new ItemLoot(item: "TricksterST0", probability: 0.0010),
                    new ItemLoot(item: "TricksterST1", probability: 0.0010),
                    new ItemLoot(item: "TricksterST2", probability: 0.0010),
                    new ItemLoot(item: "TricksterST3", probability: 0.0010),
                    new ItemLoot(item: "Edictum Praetoris", probability: 0.0010),
                    new ItemLoot(item: "Memento Mori", probability: 0.0010),
                    new ItemLoot(item: "Toga Picta", probability: 0.0010),
                    new ItemLoot(item: "Interregnum", probability: 0.0010),
                    new ItemLoot(item: "Bow of Reanimation", probability: 0.0020),
                    new ItemLoot(item: "Quiver of Reanimation", probability: 0.0020),
                    new ItemLoot(item: "Hide of Reanimation", probability: 0.0020),
                    new ItemLoot(item: "Amulet of Reanimation", probability: 0.0020),
                    new ItemLoot(item: "Pernicious Peridot", probability: 0.001),
                    new ItemLoot(item: "Acidic Armor", probability: 0.001),
                    new ItemLoot(item: "Virulent Venom", probability: 0.001),
                    new ItemLoot(item: "Dagger of Toxin", probability: 0.001),

                    new ItemLoot(item: "Kiritsukeru", probability: 0.001),
                    new ItemLoot(item: "Watarimono", probability: 0.001),
                    new ItemLoot(item: "Reinforced Root Hide", probability: 0.001),
                    new ItemLoot(item: "Traveler's Trinket", probability: 0.001)


                )
            )
            .Init("Epic Quest Chest",
                new State(
                    new ScaleHP2(100, 1, 15),
                    new State("Idle",
                        new Flash(0xFFFFFF, 0.5, 1),
                        new TimedTransition(5, "UnsetEffect")
                    ),
                    new State("UnsetEffect")
                ),
                new Threshold(0.01,
                      new ItemLoot(item: "Potion of Luck", probability: 0.5),
                    new ItemLoot(item: "Greater Potion of Luck", probability: 0.1),
                    new ItemLoot(item: "Ghost Pirate Rum", probability: 0.5),
                    new ItemLoot(item: "Coral Silk Armor", probability: 0.002),
                    new ItemLoot(item: "Coral Ring", probability: 0.05),
                    new ItemLoot(item: "Spectral Cloth Armor", probability: 0.025),
                    new ItemLoot(item: "Captain's Ring", probability: 0.05),
                    new ItemLoot(item: "Greater Potion of Defense", probability: 0.03),
                    new ItemLoot(item: "Greater Potion of Attack", probability: 0.03),
                    new ItemLoot(item: "Greater Potion of Vitality", probability: 0.03),
                    new ItemLoot(item: "Greater Potion of Wisdom", probability: 0.03),
                    new ItemLoot(item: "Greater Potion of Speed", probability: 0.03),
                    new ItemLoot(item: "Greater Potion of Dexterity", probability: 0.03),
                    new ItemLoot(item: "Greater Potion of Mana", probability: 0.03),
                    new ItemLoot(item: "Greater Potion of Life", probability: 0.03),
                    new ItemLoot(item: "Potion of Defense", probability: 0.2),
                    new ItemLoot(item: "Potion of Attack", probability: 0.2),
                    new ItemLoot(item: "Potion of Vitality", probability: 0.2),
                    new ItemLoot(item: "Potion of Wisdom", probability: 0.2),
                    new ItemLoot(item: "Potion of Speed", probability: 0.2),
                    new ItemLoot(item: "Potion of Dexterity", probability: 0.2),
                    new ItemLoot(item: "Potion of Mana", probability: 0.2),
                    new ItemLoot(item: "Potion of Life", probability: 0.2),
                    new ItemLoot(item: "Wand of Geb", probability: 0.002),
                    new ItemLoot(item: "Book of Geb", probability: 0.002),
                    new ItemLoot(item: "Shendyt of Geb", probability: 0.002),
                    new ItemLoot(item: "Geb's Ring of Wisdom", probability: 0.002),
                    new ItemLoot(item: "Indomptable", probability: 0.00125),
                    new ItemLoot(item: "Helm of Draconic Dominance", probability: 0.002),
                    new ItemLoot(item: "Zaarvox's Heart", probability: 0.002),
                    new ItemLoot(item: "Amulet of Drakefyre", probability: 0.002),
                    new ItemLoot(item: "Sentient Staff", probability: 0.001),
                    new ItemLoot(item: "Ancient Spell: Pierce", probability: 0.001),
                    new ItemLoot(item: "The Robe of Twilight", probability: 0.001),
                    new ItemLoot(item: "The Forgotten Ring", probability: 0.001),
                    new ItemLoot(item: "Wine Cellar Incantation", probability: 0.05),
                    new ItemLoot(item: "Coral Bow", probability: 0.0007),
                    new ItemLoot(item: "Coral Venom Trap", probability: 0.0007),
                    new ItemLoot(item: "Ring of the Pyramid", probability: 0.0007),
                    new ItemLoot(item: "Ring of the Sphinx", probability: 0.0007),
                    new ItemLoot(item: "Ring of the Nile", probability: 0.0007),
                    new ItemLoot(item: "Tome of Holy Protection", probability: 0.0007),
                    new ItemLoot(item: "Spirit Dagger", probability: 0.0007),
                    new ItemLoot(item: "Ghostly Prism", probability: 0.0007),
                    new ItemLoot(item: "Fire Dragon Battle Armor", probability: 0.0007),
                    new ItemLoot(item: "Water Dragon Silk Robe", probability: 0.0007),
                    new ItemLoot(item: "Pirate King's Cutlass", probability: 0.0007),
                    new ItemLoot(item: "Leaf Bow", probability: 0.0007),
                    new ItemLoot(item: "Staff of Esben", probability: 0.0007),
                    new ItemLoot(item: "Skullish Remains of Esben", probability: 0.0007),
                    new ItemLoot(item: "Spiteful Scutum", probability: 0.0007),
                    new ItemLoot(item: "Skull of Endless Torment", probability: 0.0007),
                    new ItemLoot(item: "Thousand Shot", probability: 0.0007),
                    new ItemLoot(item: "Prism of Dire Instability", probability: 0.0007),
                    new ItemLoot(item: "Midnight Star", probability: 0.0007),
                    new ItemLoot(item: "Spiteful Scutum", probability: 0.0007),
                    new ItemLoot(item: "Pirate King’s Cutlass", probability: 0.0007),
                    new ItemLoot(item: "Harmonious Harp", probability: 0.001),
                    new ItemLoot(item: "Angel's Fanfare", probability: 0.001),
                    new ItemLoot(item: "Wings of Sanctity", probability: 0.001),
                    new ItemLoot(item: "Heavenly Halo", probability: 0.001),
                    new ItemLoot(item: "Swashbuckler's Sickle", probability: 0.001),
                    new ItemLoot(item: "Tricorne of the High Seas", probability: 0.0010),
                    new ItemLoot(item: "Naval Uniform", probability: 0.0010),
                    new ItemLoot(item: "First Mate's Hook", probability: 0.0010),
                    new ItemLoot(item: "Bergenia Bow", probability: 0.0010),
                    new ItemLoot(item: "Hollyhock Hide", probability: 0.0010),
                    new ItemLoot(item: "Plant Harvester Trap", probability: 0.0010),
                    new ItemLoot(item: "Chrysanthemum Corsage", probability: 0.0010),
                    new ItemLoot(item: "Theurgy Wand", probability: 0.0010),
                    new ItemLoot(item: "Ceremonial Merlot", probability: 0.0010),
                    new ItemLoot(item: "Anointed Robe", probability: 0.0010),
                    new ItemLoot(item: "Ring of Pagan Favor", probability: 0.0010),
                    new ItemLoot(item: "Ring of the Inferno", probability: 0.0010),
                    new ItemLoot(item: "Molten Mantle", probability: 0.0010),
                    new ItemLoot(item: "Scorchium Stone", probability: 0.0010),
                    new ItemLoot(item: "Staff of Eruption", probability: 0.0010),
                    new ItemLoot(item: "Radiant Heart", probability: 0.0010),
                    new ItemLoot(item: "Luminous Armor", probability: 0.0010),
                    new ItemLoot(item: "Crystalline Kunai", probability: 0.0010),
                    new ItemLoot(item: "Quartz Cutter", probability: 0.0010),
                    new ItemLoot(item: "Null-Magic Ring", probability: 0.0010),
                    new ItemLoot(item: "Magic-Resistance Robe", probability: 0.0010),
                    new ItemLoot(item: "Kamishimo", probability: 0.0010),
                    new ItemLoot(item: "Kazekiri", probability: 0.0010),
                    new ItemLoot(item: "Garden's Leaf Armor", probability: 0.0010),
                    new ItemLoot(item: "Crown of the Garden", probability: 0.0010),
                    new ItemLoot(item: "Hallow Grass Shield", probability: 0.0010),
                    new ItemLoot(item: "Leaf Greatsword", probability: 0.0010),
                    new ItemLoot(item: "Symbiotic Ripper", probability: 0.0010),
                    new ItemLoot(item: "Parasitic Concoction", probability: 0.0010),
                    new ItemLoot(item: "Rags of the Host", probability: 0.0010),
                    new ItemLoot(item: "Hivemind Circlet", probability: 0.0010),
                    new ItemLoot(item: "Abomination's Wrath", probability: 0.0010),
                    new ItemLoot(item: "Grotesque Scepter", probability: 0.0010),
                    new ItemLoot(item: "Garment of the Beast", probability: 0.001),
                    new ItemLoot(item: "Horrific Claws", probability: 0.0010),
                    new ItemLoot(item: "KnightST2", probability: 0.0010),
                    new ItemLoot(item: "KnightST3", probability: 0.0010),
                    new ItemLoot(item: "KnightST0", probability: 0.0010),
                    new ItemLoot(item: "KnightST1", probability: 0.0010),
                    new ItemLoot(item: "KnightST5", probability: 0.0010),
                    new ItemLoot(item: "Ring of the Guardian", probability: 0.0010),
                    new ItemLoot(item: "Heavy Plated Robe", probability: 0.0010),
                    new ItemLoot(item: "Skull of Solid Defense", probability: 0.0010),
                    new ItemLoot(item: "Ancient Summoner Staff", probability: 0.0010),
                      new ItemLoot(item: "TricksterST0", probability: 0.0010),
                    new ItemLoot(item: "TricksterST1", probability: 0.0010),
                    new ItemLoot(item: "TricksterST2", probability: 0.0010),
                    new ItemLoot(item: "TricksterST3", probability: 0.0010),
                    new ItemLoot(item: "Edictum Praetoris", probability: 0.0010),
                    new ItemLoot(item: "Memento Mori", probability: 0.0010),
                    new ItemLoot(item: "Toga Picta", probability: 0.0010),
                    new ItemLoot(item: "Interregnum", probability: 0.0010),
                    new ItemLoot(item: "Supernatural Staff", probability: 0.0010),
                    new ItemLoot(item: "Spectral Spell", probability: 0.0010),
                    new ItemLoot(item: "Immortal Mantle", probability: 0.0010),
                    new ItemLoot(item: "Phantom Pendant", probability: 0.0010),
                    new ItemLoot(item: "Marble Protection Ring", probability: 0.0010),
                    new ItemLoot(item: "Lost Passion Armor", probability: 0.0010),
                    new ItemLoot(item: "Harden Helmet of Marble", probability: 0.0010),
                    new ItemLoot(item: "Sharp Hall's Claymore", probability: 0.0010)
                )
            )
          .Init("Epic ST Chest",
                new State(
                    new ScaleHP2(100, 1, 15),
                    new State("Idle",
                        new Flash(0xFFFFFF, 0.5, 1),
                        new TimedTransition(5, "UnsetEffect")
                    ),
                    new State("UnsetEffect")
                ),
                new Threshold(0.01,
                    new ItemLoot(item: "Harmonious Harp", probability: 0.00150),
                    new ItemLoot(item: "Angel's Fanfare", probability: 0.00150),
                    new ItemLoot(item: "Wings of Sanctity", probability: 0.00150),
                    new ItemLoot(item: "Heavenly Halo", probability: 0.00150),
                    new ItemLoot(item: "Pernicious Peridot", probability: 0.00150),
                    new ItemLoot(item: "Acidic Armor", probability: 0.00150),
                    new ItemLoot(item: "Virulent Venom", probability: 0.00150),
                    new ItemLoot(item: "Dagger of Toxin", probability: 0.00150),
                    new ItemLoot(item: "Kiritsukeru", probability: 0.00150),
                    new ItemLoot(item: "Watarimono", probability: 0.00150),
                    new ItemLoot(item: "Reinforced Root Hide", probability: 0.00150),
                    new ItemLoot(item: "Traveler's Trinket", probability: 0.00150),
                    new ItemLoot(item: "Swashbuckler's Sickle", probability: 0.00150),
                    new ItemLoot(item: "Tricorne of the High Seas", probability: 0.00150),
                    new ItemLoot(item: "Naval Uniform", probability: 0.00150),
                    new ItemLoot(item: "First Mate's Hook", probability: 0.00150),
                    new ItemLoot(item: "Bergenia Bow", probability: 0.00150),
                    new ItemLoot(item: "Hollyhock Hide", probability: 0.00150),
                    new ItemLoot(item: "Plant Harvester Trap", probability: 0.00150),
                    new ItemLoot(item: "Chrysanthemum Corsage", probability: 0.00150),
                    new ItemLoot(item: "Theurgy Wand", probability: 0.00150),
                    new ItemLoot(item: "Ceremonial Merlot", probability: 0.00150),
                    new ItemLoot(item: "Anointed Robe", probability: 0.00150),
                    new ItemLoot(item: "Ring of Pagan Favor", probability: 0.00150),
                    new ItemLoot(item: "Ring of the Inferno", probability: 0.00150),
                    new ItemLoot(item: "Molten Mantle", probability: 0.00150),
                    new ItemLoot(item: "Scorchium Stone", probability: 0.00150),
                    new ItemLoot(item: "Staff of Eruption", probability: 0.00150),
                    new ItemLoot(item: "Radiant Heart", probability: 0.00150),
                    new ItemLoot(item: "Luminous Armor", probability: 0.00150),
                    new ItemLoot(item: "Crystalline Kunai", probability: 0.00150),
                    new ItemLoot(item: "Quartz Cutter", probability: 0.00150),
                    new ItemLoot(item: "Null-Magic Ring", probability: 0.00150),
                    new ItemLoot(item: "Magic-Resistance Robe", probability: 0.00150),
                    new ItemLoot(item: "Kamishimo", probability: 0.00150),
                    new ItemLoot(item: "Kazekiri", probability: 0.00150),
                    new ItemLoot(item: "Garden's Leaf Armor", probability: 0.00150),
                    new ItemLoot(item: "Crown of the Garden", probability: 0.00150),
                    new ItemLoot(item: "Hallow Grass Shield", probability: 0.00150),
                    new ItemLoot(item: "Leaf Greatsword", probability: 0.00150),
                    new ItemLoot(item: "Symbiotic Ripper", probability: 0.00150),
                    new ItemLoot(item: "Parasitic Concoction", probability: 0.00150),
                    new ItemLoot(item: "Rags of the Host", probability: 0.00150),
                    new ItemLoot(item: "Hivemind Circlet", probability: 0.00150),
                    new ItemLoot(item: "Abomination's Wrath", probability: 0.00150),
                    new ItemLoot(item: "Grotesque Scepter", probability: 0.00150),
                    new ItemLoot(item: "Garment of the Beast", probability: 0.00150),
                    new ItemLoot(item: "Horrific Claws", probability: 0.00150),
                    new ItemLoot(item: "KnightST2", probability: 0.00150),
                    new ItemLoot(item: "KnightST3", probability: 0.00150),
                    new ItemLoot(item: "KnightST0", probability: 0.00150),
                    new ItemLoot(item: "KnightST1", probability: 0.00150),
                    new ItemLoot(item: "KnightST5", probability: 0.00150),
                    new ItemLoot(item: "TricksterST0", probability: 0.00150),
                    new ItemLoot(item: "TricksterST1", probability: 0.00150),
                    new ItemLoot(item: "TricksterST2", probability: 0.00150),
                    new ItemLoot(item: "TricksterST3", probability: 0.00150),
                    new ItemLoot(item: "Ring of the Guardian", probability: 0.00150),
                    new ItemLoot(item: "Heavy Plated Robe", probability: 0.00150),
                    new ItemLoot(item: "Skull of Solid Defense", probability: 0.00150),
                    new ItemLoot(item: "Ancient Summoner Staff", probability: 0.00150),
                    new ItemLoot(item: "Edictum Praetoris", probability: 0.00150),
                    new ItemLoot(item: "Memento Mori", probability: 0.00150),
                    new ItemLoot(item: "Toga Picta", probability: 0.00150),
                    new ItemLoot(item: "Interregnum", probability: 0.00150),
                    new ItemLoot(item: "Supernatural Staff", probability: 0.00150),
                    new ItemLoot(item: "Spectral Spell", probability: 0.00150),
                    new ItemLoot(item: "Immortal Mantle", probability: 0.00150),
                    new ItemLoot(item: "Phantom Pendant", probability: 0.00150),
                    new ItemLoot(item: "Marble Protection Ring", probability: 0.00150),
                    new ItemLoot(item: "Lost Passion Armor", probability: 0.00150),
                    new ItemLoot(item: "Harden Helmet of Marble", probability: 0.00150),
                    new ItemLoot(item: "Sharp Hall's Claymore", probability: 0.00150),
                    new ItemLoot(item: "Bow of Reanimation", probability: 0.00150),
                    new ItemLoot(item: "Quiver of Reanimation", probability: 0.00150),
                    new ItemLoot(item: "Hide of Reanimation", probability: 0.00150),
                    new ItemLoot(item: "Amulet of Reanimation", probability: 0.00150)
                )
            )

              .Init("Grand Master Chest",
                new State(
                    new ScaleHP2(100, 1, 15),
                    new State("Idle",
                        new Flash(0xFFFFFF, 0.5, 1),
                        new TimedTransition(5, "UnsetEffect")
                    ),
                    new State("UnsetEffect")
                ),
                new Threshold(0.01,
                    new TierLoot(tier: 12, type: ItemType.Weapon, probability: 0.055),
                    new TierLoot(tier: 13, type: ItemType.Armor, probability: 0.055),
                    new TierLoot(tier: 6, type: ItemType.Ability, probability: 0.055),
                    new TierLoot(tier: 7, type: ItemType.Ability, probability: 0.025),
                                 new ItemLoot(item: "Potion of Defense", probability: 0.2),
                    new ItemLoot(item: "Potion of Attack", probability: 0.2),
                    new ItemLoot(item: "Potion of Vitality", probability: 0.2),
                    new ItemLoot(item: "Potion of Wisdom", probability: 0.2),
                    new ItemLoot(item: "Potion of Speed", probability: 0.2),
                    new ItemLoot(item: "Potion of Dexterity", probability: 0.2),
                    new ItemLoot(item: "Potion of Mana", probability: 0.2),
                    new ItemLoot(item: "Potion of Life", probability: 0.2),
                    new ItemLoot(item: "Greater Potion of Defense", probability: 0.3),
                    new ItemLoot(item: "Greater Potion of Attack", probability: 0.3),
                    new ItemLoot(item: "Greater Potion of Vitality", probability: 0.3),
                    new ItemLoot(item: "Greater Potion of Wisdom", probability: 0.3),
                    new ItemLoot(item: "Greater Potion of Speed", probability: 0.3),
                    new ItemLoot(item: "Greater Potion of Dexterity", probability: 0.3),
                    new ItemLoot(item: "Greater Potion of Critical Chance", probability: 0.8),
                    new ItemLoot(item: "Greater Potion of Critical Damage", probability: 0.8),
                    new ItemLoot(item: "Special Crate", probability: 0.25),
                    new ItemLoot("Fragments of Void Matter", 0.02),
                    new ItemLoot("Sourcestone", 0.001),
                    new ItemLoot("Armor of Nil", 0.001),
                    new ItemLoot("Voided Quiver", 0.001),
                    new ItemLoot("Bow of the Void", 0.001),
                    new ItemLoot("Omnipotence Ring", 0.0006),
                    new ItemLoot("Disarray", 0.0006),
                    new ItemLoot("Timeworn Scepter", 0.002),
                    new ItemLoot("The Forgotten Crown", 0.001),
                    new ItemLoot("Marble Seal", 0.0006),
                    new ItemLoot("The Ancient instrument", 0.001),
                    new ItemLoot("Magical Lodestone", 0.004),
                    new ItemLoot("Sword of the Colossus", 0.001),
                    new ItemLoot("Breastplate of New Life", 0.001),
                    new ItemLoot("Vial of Pure Darkness", 0.01),
                    new ItemLoot("Robe of the Ancient Cultist", 0.004),
                    new ItemLoot("Skull of Corrupted Souls", 0.004),
                    new ItemLoot("Bloodshed Ring", 0.004),
                      new ItemLoot(item: "Potion of Luck", probability: 1),
                    new ItemLoot(item: "Greater Potion of Luck", probability: 0.1),
                    new ItemLoot("Staff of Unholy Sacrifice", 0.004)


                )
            )

           .Init("Grand Champion Chest",
                new State(
                    new ScaleHP2(100, 1, 15),
                    new State("Idle",
                        new Flash(0xFFFFFF, 0.5, 1),
                        new TimedTransition(5, "UnsetEffect")
                    ),
                    new State("UnsetEffect")
                ),
                new Threshold(0.01,
                    new ItemLoot(item: "Ghost Pirate Rum", probability: 0.5),
                    new ItemLoot(item: "Coral Silk Armor", probability: 0.002),
                    new ItemLoot(item: "Coral Ring", probability: 0.05),
                    new ItemLoot(item: "Spectral Cloth Armor", probability: 0.025),
                    new ItemLoot(item: "Captain's Ring", probability: 0.05),
                    new ItemLoot(item: "Wand of Geb", probability: 0.002),
                    new ItemLoot(item: "Book of Geb", probability: 0.002),
                    new ItemLoot(item: "Shendyt of Geb", probability: 0.002),
                    new ItemLoot(item: "Geb's Ring of Wisdom", probability: 0.002),
                    new ItemLoot(item: "Indomptable", probability: 0.00125),
                    new ItemLoot(item: "Helm of Draconic Dominance", probability: 0.002),
                    new ItemLoot(item: "Zaarvox's Heart", probability: 0.002),
                    new ItemLoot(item: "Amulet of Drakefyre", probability: 0.002),
                    new ItemLoot(item: "Sentient Staff", probability: 0.001),
                    new ItemLoot(item: "Ancient Spell: Pierce", probability: 0.001),
                    new ItemLoot(item: "The Robe of Twilight", probability: 0.001),
                    new ItemLoot(item: "The Forgotten Ring", probability: 0.001),
                    new ItemLoot(item: "Wine Cellar Incantation", probability: 0.05),
                    new ItemLoot(item: "Coral Bow", probability: 0.0007),
                    new ItemLoot(item: "Coral Venom Trap", probability: 0.0007),
                    new ItemLoot(item: "Ring of the Pyramid", probability: 0.0007),
                    new ItemLoot(item: "Ring of the Sphinx", probability: 0.0007),
                    new ItemLoot(item: "Ring of the Nile", probability: 0.0007),
                    new ItemLoot(item: "Tome of Holy Protection", probability: 0.0007),
                    new ItemLoot(item: "Spirit Dagger", probability: 0.0007),
                    new ItemLoot(item: "Ghostly Prism", probability: 0.0007),
                    new ItemLoot(item: "Fire Dragon Battle Armor", probability: 0.0007),
                    new ItemLoot(item: "Water Dragon Silk Robe", probability: 0.0007),
                    new ItemLoot(item: "Pirate King's Cutlass", probability: 0.0007),
                    new ItemLoot(item: "Leaf Bow", probability: 0.0007),
                    new ItemLoot(item: "Staff of Esben", probability: 0.0007),
                    new ItemLoot(item: "Skullish Remains of Esben", probability: 0.0007),
                    new ItemLoot(item: "Spiteful Scutum", probability: 0.0007),
                    new ItemLoot(item: "Skull of Endless Torment", probability: 0.0007),
                    new ItemLoot(item: "Thousand Shot", probability: 0.0007),
                    new ItemLoot(item: "Prism of Dire Instability", probability: 0.0007),
                    new ItemLoot(item: "Midnight Star", probability: 0.0007),
                    new ItemLoot(item: "Spiteful Scutum", probability: 0.0007),
                    new ItemLoot(item: "Pirate King’s Cutlass", probability: 0.0007),
                    new ItemLoot(item: "Harmonious Harp", probability: 0.001),
                    new ItemLoot(item: "Angel's Fanfare", probability: 0.001),
                    new ItemLoot(item: "Wings of Sanctity", probability: 0.001),
                    new ItemLoot(item: "Heavenly Halo", probability: 0.001),
                    new ItemLoot(item: "Swashbuckler's Sickle", probability: 0.001),
                    new ItemLoot(item: "Tricorne of the High Seas", probability: 0.0010),
                    new ItemLoot(item: "Naval Uniform", probability: 0.0010),
                    new ItemLoot(item: "First Mate's Hook", probability: 0.0010),
                    new ItemLoot(item: "Bergenia Bow", probability: 0.0010),
                    new ItemLoot(item: "Hollyhock Hide", probability: 0.0010),
                    new ItemLoot(item: "Plant Harvester Trap", probability: 0.0010),
                    new ItemLoot(item: "Chrysanthemum Corsage", probability: 0.0010),
                    new ItemLoot(item: "Theurgy Wand", probability: 0.0010),
                    new ItemLoot(item: "Ceremonial Merlot", probability: 0.0010),
                    new ItemLoot(item: "Anointed Robe", probability: 0.0010),
                    new ItemLoot(item: "Ring of Pagan Favor", probability: 0.0010),
                    new ItemLoot(item: "Ring of the Inferno", probability: 0.0010),
                    new ItemLoot(item: "Molten Mantle", probability: 0.0010),
                    new ItemLoot(item: "Scorchium Stone", probability: 0.0010),
                    new ItemLoot(item: "Staff of Eruption", probability: 0.0010),
                    new ItemLoot(item: "Radiant Heart", probability: 0.0010),
                    new ItemLoot(item: "Luminous Armor", probability: 0.0010),
                    new ItemLoot(item: "Crystalline Kunai", probability: 0.0010),
                    new ItemLoot(item: "Quartz Cutter", probability: 0.0010),
                    new ItemLoot(item: "Null-Magic Ring", probability: 0.0010),
                    new ItemLoot(item: "Magic-Resistance Robe", probability: 0.0010),
                    new ItemLoot(item: "Kamishimo", probability: 0.0010),
                    new ItemLoot(item: "Kazekiri", probability: 0.0010),
                    new ItemLoot(item: "Garden's Leaf Armor", probability: 0.0010),
                    new ItemLoot(item: "Crown of the Garden", probability: 0.0010),
                    new ItemLoot(item: "Hallow Grass Shield", probability: 0.0010),
                    new ItemLoot(item: "Leaf Greatsword", probability: 0.0010),
                    new ItemLoot(item: "Symbiotic Ripper", probability: 0.0010),
                    new ItemLoot(item: "Parasitic Concoction", probability: 0.0010),
                    new ItemLoot(item: "Rags of the Host", probability: 0.0010),
                    new ItemLoot(item: "Hivemind Circlet", probability: 0.0010),
                    new ItemLoot(item: "Abomination's Wrath", probability: 0.0010),
                    new ItemLoot(item: "Grotesque Scepter", probability: 0.0010),
                    new ItemLoot(item: "Garment of the Beast", probability: 0.001),
                    new ItemLoot(item: "Horrific Claws", probability: 0.0010),
                    new ItemLoot(item: "KnightST2", probability: 0.0010),
                    new ItemLoot(item: "KnightST3", probability: 0.0010),
                    new ItemLoot(item: "KnightST0", probability: 0.0010),
                    new ItemLoot(item: "KnightST1", probability: 0.0010),
                    new ItemLoot(item: "KnightST5", probability: 0.0010),
                    new ItemLoot(item: "Ring of the Guardian", probability: 0.0010),
                    new ItemLoot(item: "Heavy Plated Robe", probability: 0.0010),
                    new ItemLoot(item: "Skull of Solid Defense", probability: 0.0010),
                    new ItemLoot(item: "Ancient Summoner Staff", probability: 0.0010),
                    new ItemLoot(item: "TricksterST0", probability: 0.0010),
                    new ItemLoot(item: "TricksterST1", probability: 0.0010),
                    new ItemLoot(item: "TricksterST2", probability: 0.0010),
                    new ItemLoot(item: "TricksterST3", probability: 0.0010),
                    new ItemLoot(item: "Edictum Praetoris", probability: 0.0010),
                    new ItemLoot(item: "Memento Mori", probability: 0.0010),
                    new ItemLoot(item: "Toga Picta", probability: 0.0010),
                    new ItemLoot(item: "Interregnum", probability: 0.0010),
                    new ItemLoot(item: "Supernatural Staff", probability: 0.0010),
                    new ItemLoot(item: "Spectral Spell", probability: 0.0010),
                    new ItemLoot(item: "Immortal Mantle", probability: 0.0010),
                    new ItemLoot(item: "Phantom Pendant", probability: 0.0010),
                    new ItemLoot(item: "Marble Protection Ring", probability: 0.0010),
                    new ItemLoot(item: "Lost Passion Armor", probability: 0.0010),
                    new ItemLoot(item: "Harden Helmet of Marble", probability: 0.0010),
                    new ItemLoot(item: "Sharp Hall's Claymore", probability: 0.0010),
                    new TierLoot(tier: 12, type: ItemType.Weapon, probability: 0.055),
                    new TierLoot(tier: 13, type: ItemType.Armor, probability: 0.055),
                    new TierLoot(tier: 6, type: ItemType.Ability, probability: 0.055),
                    new TierLoot(tier: 7, type: ItemType.Ability, probability: 0.025),
                                 new ItemLoot(item: "Potion of Defense", probability: 0.2),
                    new ItemLoot(item: "Potion of Attack", probability: 0.2),
                    new ItemLoot(item: "Potion of Vitality", probability: 0.2),
                    new ItemLoot(item: "Potion of Wisdom", probability: 0.2),
                    new ItemLoot(item: "Potion of Speed", probability: 0.2),
                    new ItemLoot(item: "Potion of Dexterity", probability: 0.2),
                    new ItemLoot(item: "Potion of Mana", probability: 0.2),
                    new ItemLoot(item: "Potion of Life", probability: 0.2),
                    new ItemLoot(item: "Greater Potion of Defense", probability: 0.3),
                    new ItemLoot(item: "Greater Potion of Attack", probability: 0.3),
                    new ItemLoot(item: "Greater Potion of Vitality", probability: 0.3),
                    new ItemLoot(item: "Greater Potion of Wisdom", probability: 0.3),
                    new ItemLoot(item: "Greater Potion of Speed", probability: 0.3),
                    new ItemLoot(item: "Greater Potion of Dexterity", probability: 0.3),
                    new ItemLoot(item: "Greater Potion of Critical Chance", probability: 0.3),
                    new ItemLoot(item: "Greater Potion of Critical Damage", probability: 0.3),
                    new ItemLoot("Magical Soul Hide", 0.004),
                    new ItemLoot("Book of Crystal Protection", 0.004),
                    new ItemLoot("Fragments of Void Matter", 0.02),
                    new ItemLoot("Sourcestone", 0.001),
                    new ItemLoot("Armor of Nil", 0.001),
                    new ItemLoot("Voided Quiver", 0.001),
                    new ItemLoot("Bow of the Void", 0.001),
                    new ItemLoot("Omnipotence Ring", 0.0006),
                    new ItemLoot("Disarray", 0.0006),
                    new ItemLoot("Timeworn Scepter", 0.001),
                    new ItemLoot("The Forgotten Crown", 0.001),
                    new ItemLoot("Marble Seal", 0.0006),
                    new ItemLoot("The Ancient instrument", 0.001),
                    new ItemLoot("Magical Lodestone", 0.004),
                    new ItemLoot("Sword of the Colossus", 0.001),
                    new ItemLoot("Breastplate of New Life", 0.001),
                    new ItemLoot("Vial of Pure Darkness", 0.003, 1),
                    new ItemLoot("Robe of the Ancient Cultist", 0.004),
                    new ItemLoot("Skull of Corrupted Souls", 0.004),
                    new ItemLoot("Bloodshed Ring", 0.004),
                    new ItemLoot("Staff of Unholy Sacrifice", 0.004),
                    new ItemLoot("Cultist Chest Item", 0.0045),
                    new ItemLoot("Forgotten King Chest Item", 0.0045),
                    new ItemLoot("Void Entity Chest Item", 0.0045),
                    new ItemLoot("Marble Colossus Chest Item", 0.0045),
                      new ItemLoot(item: "Potion of Luck", probability: 1),
                    new ItemLoot(item: "Greater Potion of Luck", probability: 0.1)


                )
            )

          .Init("Cultist Chest",
                new State(
                    new ScaleHP2(100, 1, 15),
                    new State("Idle",
                        new Flash(0xFFFFFF, 0.5, 1),
                        new TimedTransition(5, "UnsetEffect")
                    ),
                    new State("UnsetEffect")
                ),
                 new Threshold(0.01,
                    new TierLoot(9, ItemType.Weapon, 0.375),
                    new TierLoot(10, ItemType.Weapon, 0.325),
                    new TierLoot(11, ItemType.Weapon, 0.18),
                    new TierLoot(10, ItemType.Armor, 0.25),
                    new TierLoot(11, ItemType.Armor, 0.1),
                    new TierLoot(12, ItemType.Armor, 0.15),
                    new TierLoot(4, ItemType.Ability, 0.25),
                    new TierLoot(5, ItemType.Ability, 0.2),
                    new TierLoot(5, ItemType.Ring, 0.25),
                    new ItemLoot(item: "Greater Potion of Defense", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Attack", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Vitality", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Wisdom", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Speed", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Dexterity", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Mana", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Life", probability: 0.1),
                    new ItemLoot(item: "Potion of Defense", probability: 1),
                    new ItemLoot(item: "Potion of Attack", probability: 1),
                    new ItemLoot(item: "Potion of Vitality", probability: 1),
                    new ItemLoot(item: "Potion of Wisdom", probability: 1),
                    new ItemLoot(item: "Potion of Speed", probability: 0.2),
                    new ItemLoot(item: "Potion of Dexterity", probability: 0.23),
                    new ItemLoot(item: "Potion of Mana", probability: 1),
                    new ItemLoot(item: "Potion of Life", probability: 0.2),
                      new ItemLoot(item: "Potion of Luck", probability: 1),
                    new ItemLoot(item: "Greater Potion of Luck", probability: 0.1),
                    new ItemLoot("Potion of Critical Chance", 0.2),
                    new ItemLoot("Potion of Critical Damage", 0.2),//Vial of Pure Darkness
                    new ItemLoot("Vial of Pure Darkness", 0.005, 1),
                    new ItemLoot("Robe of the Ancient Cultist", 0.005),
                    new ItemLoot("Skull of Corrupted Souls", 0.005),
                    new ItemLoot("Bloodshed Ring", 0.005),
                    new ItemLoot("Staff of Unholy Sacrifice", 0.005)

                )
            )
          .Init("Forgotten King Chest",
                new State(
                    new ScaleHP2(100, 1, 15),
                    new State("Idle",
                        new Flash(0xFFFFFF, 0.5, 1),
                        new TimedTransition(5, "UnsetEffect")
                    ),
                    new State("UnsetEffect")
                ),
                  new Threshold(0.01,
                     new ItemLoot(item: "Greater Potion of Defense", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Attack", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Vitality", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Wisdom", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Speed", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Dexterity", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Mana", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Life", probability: 0.1),
                    new ItemLoot(item: "Potion of Defense", probability: 1),
                    new ItemLoot(item: "Potion of Attack", probability: 1),
                    new ItemLoot(item: "Potion of Vitality", probability: 0.2),
                    new ItemLoot(item: "Potion of Wisdom", probability: 0.2),
                    new ItemLoot(item: "Potion of Speed", probability: 0.2),
                    new ItemLoot(item: "Potion of Dexterity", probability: 0.23),
                    new ItemLoot(item: "Potion of Mana", probability: 0.2),
                    new ItemLoot(item: "Potion of Life", probability: 1),
                    new ItemLoot(item: "Potion of Luck", probability: 1),
                    new ItemLoot(item: "Greater Potion of Luck", probability: 0.1),
                    new ItemLoot("Potion of Critical Chance", 0.2),
                    new ItemLoot("Potion of Critical Damage", 0.2),
                    new TierLoot(11, ItemType.Weapon, 0.1625),
                    new TierLoot(12, ItemType.Weapon, 0.13125),
                    new TierLoot(12, ItemType.Armor, 0.1625),
                    new TierLoot(13, ItemType.Armor, 0.13125),
                    new TierLoot(6, ItemType.Armor, 0.13125),
                    new TierLoot(6, ItemType.Ring, 0.13125),
                    new ItemLoot("Timeworn Scepter", 0.002),
                    new ItemLoot("The Forgotten Crown", 0.002)
                )
            )
         .Init("Void Entity Chest",
                new State(
                    new ScaleHP2(100, 1, 15),
                    new State("Idle",
                        new Flash(0xFFFFFF, 0.5, 1),
                        new TimedTransition(5, "UnsetEffect")
                    ),
                    new State("UnsetEffect")
                ),
             new Threshold(0.01,
                    new TierLoot(12, ItemType.Weapon, 0.024),
                    new TierLoot(13, ItemType.Armor, 0.024),
                    new TierLoot(6, ItemType.Ability, 0.24),
                    new TierLoot(6, ItemType.Ring, 0.16),
                    new ItemLoot(item: "Greater Potion of Defense", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Attack", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Vitality", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Wisdom", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Speed", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Dexterity", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Mana", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Life", probability: 0.1),
                    new ItemLoot(item: "Potion of Defense", probability: 0.2),
                    new ItemLoot(item: "Potion of Attack", probability: 0.2),
                    new ItemLoot(item: "Potion of Vitality", probability: 0.2),
                    new ItemLoot(item: "Potion of Wisdom", probability: 1),
                    new ItemLoot(item: "Potion of Speed", probability: 0.2),
                    new ItemLoot(item: "Potion of Dexterity", probability: 0.23),
                    new ItemLoot(item: "Potion of Mana", probability: 0.2),
                    new ItemLoot(item: "Potion of Life", probability: 1),
                      new ItemLoot(item: "Potion of Luck", probability: 1),
                    new ItemLoot(item: "Greater Potion of Luck", probability: 0.1),
                    new ItemLoot("Potion of Critical Chance", 0.2),
                    new ItemLoot("Potion of Critical Damage", 0.2),
                    new ItemLoot("Fragments of Void Matter", 0.03),
                    new ItemLoot("Sourcestone", 0.002),
                    new ItemLoot("Armor of Nil", 0.002),
                    new ItemLoot("Voided Quiver", 0.002),
                    new ItemLoot("Bow of the Void", 0.002),
                    new ItemLoot("Omnipotence Ring", 0.0008)
                )
            )
         .Init("Marble Colossus Chest",
                new State(
                    new ScaleHP2(100, 1, 15),
                    new State("Idle",
                        new Flash(0xFFFFFF, 0.5, 1),
                        new TimedTransition(5, "UnsetEffect")
                    ),
                    new State("UnsetEffect")
                ),
             new Threshold(0.01,
                    new TierLoot(12, ItemType.Weapon, 0.015),
                    new TierLoot(13, ItemType.Armor, 0.015),
                    new TierLoot(6, ItemType.Ability, 0.15),
                    new TierLoot(5, ItemType.Ring, 0.15),
                    new TierLoot(6, ItemType.Ring, 0.1),
                    new TierLoot(7, ItemType.Ring, 0.05),
                    new ItemLoot(item: "Greater Potion of Defense", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Attack", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Vitality", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Wisdom", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Speed", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Dexterity", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Mana", probability: 0.1),
                    new ItemLoot(item: "Greater Potion of Life", probability: 0.1),
                    new ItemLoot(item: "Potion of Defense", probability: 0.2),
                    new ItemLoot(item: "Potion of Attack", probability: 0.2),
                    new ItemLoot(item: "Potion of Vitality", probability: 0.2),
                    new ItemLoot(item: "Potion of Wisdom", probability: 1),
                    new ItemLoot(item: "Potion of Speed", probability: 0.2),
                    new ItemLoot(item: "Potion of Dexterity", probability: 0.23),
                    new ItemLoot(item: "Potion of Mana", probability: 0.2),
                    new ItemLoot(item: "Potion of Life", probability: 1),
                      new ItemLoot(item: "Potion of Luck", probability: 1),
                    new ItemLoot(item: "Greater Potion of Luck", probability: 0.1),
                    new ItemLoot("Potion of Critical Chance", 0.2),
                    new ItemLoot("Potion of Critical Damage", 0.2),
                    new ItemLoot("Marble Seal", 0.0008),
                    new ItemLoot("The Ancient instrument", 0.002),
                    new ItemLoot("Magical Lodestone", 0.004),
                    new ItemLoot("Sword of the Colossus", 0.002),
                    new ItemLoot("Breastplate of New Life", 0.002)
                )
            );

    }
}